import { createContext, useContext, useState, ReactNode } from "react"

type Language = "ko" | "en"

interface LanguageContextType {
  language: Language
  toggleLanguage: () => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  ko: {
    // Header
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.inquiry": "문의하기",
    "nav.works": "WORKS",
    "nav.lineup": "LINEUP 147",
    "nav.blog": "BLOG",
    "nav.faq": "FAQ",
    
    // Home
    "home.hero.title": "소복",
    "home.hero.subtitle": "브랜드의 감성을 포장하는 가장 간결한 방식",
    "home.hero.cta": "커스텀 제작 문의하기",
    
    // Home - Who we are
    "home.who.title": "Who we are",
    "home.who.main": "상품을 포장하지 않습니다.",
    "home.who.sub": "브랜드를 포장합니다.",
    "home.who.desc": "포장은 단순한 포장지가 아닙니다. 존중의 표현이자, 배려의 몸짓이며, 감정의 전달입니다.\n\n한국의 전통에서 보자기는 단순한 천 이상의 의미를 지닙니다. 선물하는 이의 정성과 마음가짐을 담아냅니다. 매 접힘과 매듭마다 의도가 담겨 있습니다.\n\n소복은 작지만 확실한 축복을 뜻하며, 눈처럼 조용히 쌓입니다. 우리의 접근 방식도 같습니다. 은은하지만, 의도적이며, 오래 남습니다.",
    
    // Home - Service Introduction
    "home.service.title": "맞춤형 보자기 제작 서비스",
    "home.service.desc": "SOBOK은 브랜드의 아이덴티티를 담은 맞춤형 보자기와 포장 소모품을 제작합니다. 리테일 브랜드, 선물 전문 브랜드, 이벤트 기획사 등 다양한 고객에게 브랜드 톤앤매너에 맞는 포장 솔루션을 제공합니다.",
    
    // Home - Strengths
    "home.strengths.title": "SOBOK의 강점",
    "home.strengths.weaving.title": "직조 기반 맞춤 패턴 제작 가능",
    "home.strengths.weaving.desc": "브랜드의 패턴과 로고를 직접 직조하여 완전히 독특한 보자기를 제작할 수 있습니다.",
    "home.strengths.experience.title": "브랜드 전용 보자기 제작 경험",
    "home.strengths.experience.desc": "다수의 브랜드와 협업한 경험을 바탕으로 프로젝트 성격에 맞는 최적의 솔루션을 제안합니다.",
    "home.strengths.materials.title": "다양한 소재 제공",
    "home.strengths.materials.desc": "슬라브, 오간자, 크리스탈 등 다양한 소재를 제공하여 프로젝트의 목적과 예산에 맞는 선택이 가능합니다.",
    "home.strengths.consultation.title": "상담 기반 프로세스",
    "home.strengths.consultation.desc": "부담 없이 문의하실 수 있으며, 담당자가 직접 연락하여 상세한 상담을 진행합니다.",
    
    // Home - Bojagi Types
    "home.bojagi.title": "보자기 종류 안내",
    "home.bojagi.regular.title": "일반 보자기",
    "home.bojagi.regular.slab.title": "슬라브",
    "home.bojagi.regular.slab.desc": "자연스러운 결과 따뜻한 느낌을 주는 소재입니다.",
    "home.bojagi.regular.organza.title": "오간자",
    "home.bojagi.regular.organza.desc": "반투명한 고급스러운 분위기를 연출할 수 있습니다.",
    "home.bojagi.regular.crystal.title": "크리스탈",
    "home.bojagi.regular.crystal.desc": "광택감이 있어 행사나 프로모션용 대량 제작에 적합합니다.",
    "home.bojagi.brand.title": "브랜드 직조 보자기",
    "home.bojagi.brand.desc": "브랜드가 보유한 패턴, 로고, 심볼을 기반으로 패브릭을 직접 직조합니다. 디자인 파일을 전달받아 목업을 제작한 뒤 제안드립니다.",
    
    // Home - Packaging Supplies
    "home.supplies.title": "포장 소모품 안내",
    "home.supplies.desc": "스티커, 리본, 쇼핑백, 박스 등 패키지 관련 소모품도 함께 제작 가능합니다. 브랜드 톤앤매너에 맞춰 통일감 있는 패키징 구성이 가능합니다.",
    
    // Home - Process
    "home.process.title": "진행과정",
    "home.process.subtitle": "정성스러운 선물을 위한 정성스러운 과정",
    "home.process.step1.title": "브랜드 컨설팅",
    "home.process.step1.desc": "귀사의 브랜드, 가치, 포장의 목적을 상세히 파악하는 맞춤 상담을 진행합니다.",
    "home.process.step1.features": "브랜드 전략\n비전 설정\n콘셉트 정의",
    "home.process.step2.title": "디자인 & 시제품",
    "home.process.step2.desc": "브랜드 아이덴티티를 반영한 디자인을 제안하고 시제품을 제작합니다.",
    "home.process.step2.features": "디자인 제안\n시제품 제작\n피드백 반영",
    "home.process.step3.title": "직조 & 제작",
    "home.process.step3.desc": "확정된 디자인을 바탕으로 전문 장인이 직접 직조하고 제작합니다.",
    "home.process.step3.features": "원단 선택\n직조 작업\n품질 검수",
    "home.process.step4.title": "본 생산 & 배송",
    "home.process.step4.desc": "전문적인 포장과 함께 지정된 장소로 정시 배송해 드립니다.",
    "home.process.step4.features": "생산 관리\n납기 일정\n물류 배송",
    "home.process.step5.title": "아카이빙 & 재주문 서비스",
    "home.process.step5.desc": "귀사의 데이터를 보관하여 향후 간편한 재주문이 가능합니다.",
    "home.process.step5.features": "데이터 관리\n재생산 요청\n주문 이력",
    
    // Home - Services Feature
    "home.services.feature.title": "Wrapped with Sincerity",
    "home.services.feature.subtitle": "보자기 한 장으로 브랜드의 이야기를 완성합니다.",
    "home.services.easy.title": "Easy",
    "home.services.easy.korean": "쉽고 편리하게",
    "home.services.easy.desc": "필요한 보자기를 빠르게, 번거로움 없이, 브랜드별 맞춤 직조와 다양한 소재 옵션을 통해 복잡한 제작 과정과 불필요한 자재 낭비를 줄여드립니다.",
    "home.services.proven.title": "Proven",
    "home.services.proven.korean": "검증된 품질과 과정",
    "home.services.proven.desc": "디자인부터 직조, 포장, 납품까지 모든 단계를 체계적으로 관리합니다. 수많은 브랜드 프로젝트로 검증된 생산 네트워크와 데이터 기반 공정 관리로 안정적인 결과를 제공합니다.",
    "home.services.reliable.title": "Reliable",
    "home.services.reliable.korean": "믿을 수 있는 파트너",
    "home.services.reliable.desc": "브랜드가 원하는 퀄리티를 정확하게 이해하고 책임 있게 제작합니다. 일정, 품질, 비용을 투명하게 공유하며 납품까지 신뢰할 수 있는 파트너로 함께합니다.",
    "home.services.custom.title": "맞춤 제작 보자기",
    "home.services.custom.percent": "최대 25%",
    "home.services.custom.price": "낮은 단가로 제작",
    "home.services.custom.desc": "브랜드별 맞춤 직조로 불필요한 자재 낭비를 줄입니다.",
    "home.services.quality.title": "일정과 품질 관리 시스템",
    "home.services.quality.delivery": "납품 일정",
    "home.services.quality.guarantee": "100% 보장",
    "home.services.quality.desc": "디자인, 직조, 포장, 납품까지 모든 공정을 데이터 기반으로 관리합니다.",
    "home.services.partners": "소복과 함께 브랜드의 마음을 정해온 기업입니다.",
    
    // Home - CTA
    "home.cta.title": "지금 문의하세요",
    "home.cta.subtitle": "당신의 브랜드엔 어떤 천이 어울릴까요?",
    "home.cta.desc": "보자기 한 장으로 브랜드의 이야기를 완성합니다.",
    "home.cta.footer": "포장은 단순한 마감이 아니라, 브랜드의 시작입니다.",
    "home.cta.button": "문의하기",
    
    "home.lineup.title": "브랜드 기획부터 생산까지 SOBOK에서\n다 준비해 놨으니까",
    "home.lineup.subtitle": "상품기획자, 디자이너 없이도\n바로 뷰티 브랜드 런칭이 가능하도록, LINEUP 147",
    "home.lineup.cta": "LINEUP 147 주문하러 가기",
    
    "home.loudlabs.title": "진짜 시장이 원하는\n브랜드를 만듭니다.",
    "home.loudlabs.subtitle": "AI 기술로 시장 트렌드와 상품의 맥락을 파악하고\n이를 활용하여 새로운 상품을 기획하는 LoudLabs",
    "home.loudlabs.cta": "라우드랩스 체험하러 가기",
    
    "home.features.easy.title": "Easy",
    "home.features.easy.subtitle": "쉽고",
    "home.features.easy.desc": "고객의 쉽고 빠른 뷰티 비즈니스를 위하여 브랜딩부터 기획, 생산까지 전 영역에 걸쳐 서비스를 제공합니다.",
    "home.features.proven.title": "Proven",
    "home.features.proven.subtitle": "검증된",
    "home.features.proven.desc": "브랜드 기획자와 연구원 출신의 전문가가 기획하고 실제 시장에 테스트하며 기획력을 검증합니다.",
    "home.features.reliable.title": "Reliable",
    "home.features.reliable.subtitle": "믿을 수 있는",
    "home.features.reliable.desc": "머신러닝을 기반으로 개발한 상품 모형 평가 및 예측 알고리즘을 토대로 고객에게 제안합니다.",
    
    "home.newsletter.title": "SOBOK LETTER",
    "home.newsletter.subtitle": "뷰티 브랜드 인큐베이터",
    "home.newsletter.desc": "SOBOK에서 전하는 화장품 이야기",
    "home.newsletter.placeholder": "이메일을 입력하세요",
    "home.newsletter.cta": "SOBOK LETTER 뉴스레터 신청하기",
    
    "home.update.title": "새롭게 업데이트 된 Lineup 147",
    "home.update.cta": "자세히 보기",
    "home.update.brand.milkdive": "밀크다이브",
    "home.update.brand.puresource": "퓨어소스",
    "home.update.desc.milkdive": "피부가 우유를 마실 수 있는 재밌는 상상",
    "home.update.desc.puresource": "검증된 출처와 최적의 배합의 더마 브랜드",
    "home.update.launchable": "런칭가능",
    
    // About
    "about.title": "ABOUT SOBOK",
    "about.intro.title": "브랜드 소개",
    "about.intro.desc": "SOBOK은 포장을 통해 순간을 더 오래 기억하게 만들고 싶다는 생각으로 시작된 브랜드입니다. 전통적인 보자기 문화와 현대적인 브랜드 패키지를 연결하는 역할을 합니다.",
    "about.culture.title": "포장 문화에 대한 관점",
    "about.culture.desc": "한국의 보자기 문화는 선물을 감싸는 행위 자체에 의미를 부여하는 독특한 전통입니다. SOBOK은 이러한 전통의 가치를 현대적인 브랜드 경험에 접목하여, 단순한 포장을 넘어선 감성적 가치를 제공합니다.",
    "about.values.title": "SOBOK이 제공하는 가치",
    "about.values.custom.title": "브랜드 아이덴티티를 담는 맞춤 패턴",
    "about.values.custom.desc": "브랜드의 고유한 패턴과 로고를 직접 직조하여 완전히 독특한 보자기를 제작합니다.",
    "about.values.trust.title": "제작 공정과 품질에 대한 신뢰",
    "about.values.trust.desc": "검증된 제작 공정과 품질 관리를 통해 일관된 품질의 제품을 제공합니다.",
    "about.values.flexible.title": "프로젝트 성격에 맞춘 유연한 제안",
    "about.values.flexible.desc": "리테일 브랜드 시즌 프로모션 패키지부터 기념일/행사용 선물 패키지까지, 다양한 프로젝트에 맞춘 솔루션을 제안합니다.",
    "about.cases.title": "제작 사례",
    "about.cases.retail": "리테일 브랜드 시즌 프로모션 패키지",
    "about.cases.event": "기념일/행사용 선물 패키지",
    "about.cta.title": "함께 시작해볼까요?",
    "about.cta.desc": "SOBOK과 함께 브랜드만의 특별한 포장 솔루션을 만들어보세요",
    "about.cta.button": "문의하기",
    
    // Inquiry
    "inquiry.title": "상담·견적 문의",
    "inquiry.subtitle": "프로젝트에 맞는 보자기 제작을 위해 문의 양식을 작성해주세요",
    "inquiry.overview.title": "상담 전 다시 한번 확인해주세요!",
    "inquiry.overview.point1": "소복은 브랜딩과 패키지 디자인에 집중하며, 더욱 효율적이고 감각적인 보자기 개발이 가능한 서비스입니다.",
    "inquiry.overview.point2": "상담 신청 후 바로 결제와 생산이 진행되지 않습니다.",
    "inquiry.overview.point3": "소복 전문가가 영업일 3일 이내로 연락 드릴 예정입니다.",
    "inquiry.profile.title": "회사 및 담당자 정보",
    "inquiry.profile.requiredNote": "는 필수 입력 정보입니다.",
    "inquiry.company.title": "회사 정보",
    "inquiry.company.name": "회사명",
    "inquiry.company.name.required": "필수",
    "inquiry.company.name.placeholder": "사업자명 또는 브랜드명을 입력해 주세요.",
    "inquiry.company.website": "회사 홈페이지 주소",
    "inquiry.company.website.placeholder": "홈페이지 또는 인스타그램, 스마트스토어 등 온라인 채널 주소를 남겨주셔도 좋습니다.",
    "inquiry.company.country": "국가",
    "inquiry.company.country.placeholder": "국가를 선택해 주세요.",
    "inquiry.company.industry": "산업군",
    "inquiry.company.industry.placeholder": "산업군을 선택하거나 직접 입력해 주세요.",
    "inquiry.company.industry.custom": "산업군 직접 입력",
    "inquiry.company.industry.custom.placeholder": "예) 웰니스, 퍼퓸, 리빙 등",
    "inquiry.company.products": "기존 판매 제품",
    "inquiry.company.products.placeholder": "현재 판매 중이거나 출시 예정인 제품을 간단히 적어주세요.",
    "inquiry.bojagi.title": "보자기 종류",
    "inquiry.bojagi.regular": "일반 보자기",
    "inquiry.bojagi.regular.slab": "슬라브",
    "inquiry.bojagi.regular.slab.desc": "자연스러운 결과 따뜻한 느낌",
    "inquiry.bojagi.regular.organza": "오간자",
    "inquiry.bojagi.regular.organza.desc": "반투명한 고급스러운 분위기",
    "inquiry.bojagi.regular.crystal": "크리스탈",
    "inquiry.bojagi.regular.crystal.desc": "광택감, 행사·프로모션용 대량 제작 적합",
    "inquiry.bojagi.brand": "브랜드 직조 보자기",
    "inquiry.bojagi.brand.desc": "브랜드 패턴, 로고, 심볼 등을 활용한 직조 보자기 제작이 가능합니다.",
    "inquiry.bojagi.brand.file": "디자인 파일이 있다면 첨부해 주세요. 목업 제작 및 제안에 활용됩니다.",
    "inquiry.bojagi.size.label": "사이즈",
    "inquiry.bojagi.size.description": "가로 X 세로 (cm 단위)로 입력해주세요. 확정되지 않았다면 예상 사이즈를 입력하셔도 좋습니다.",
    "inquiry.bojagi.size.width": "가로(cm)",
    "inquiry.bojagi.size.height": "세로(cm)",
    "inquiry.bojagi.size.width.placeholder": "예: 70",
    "inquiry.bojagi.size.height.placeholder": "예: 70",
    "inquiry.supplies.title": "포장 소모품",
    "inquiry.supplies.quantity": "필요 수량",
    "inquiry.supplies.quantity.placeholder": "예상 수량을 입력해주세요",
    "inquiry.supplies.deadline": "납기 희망일",
    "inquiry.supplies.deadline.placeholder": "희망 납기일을 입력해주세요",
    "inquiry.supplies.budget": "총 예산",
    "inquiry.supplies.budget.placeholder": "예상 예산을 입력해주세요 (선택사항)",
    "inquiry.supplies.budget.unit": "원",
    "inquiry.contact.title": "담당자 정보",
    "inquiry.contact.name": "담당자명",
    "inquiry.contact.name.required": "필수",
    "inquiry.contact.name.placeholder": "이름을 입력해주세요.",
    "inquiry.contact.email": "이메일",
    "inquiry.contact.email.required": "필수",
    "inquiry.contact.email.placeholder": "이메일 주소를 입력해주세요.",
    "inquiry.contact.phone": "연락처",
    "inquiry.contact.phone.required": "필수",
    "inquiry.contact.phone.placeholder": "연락처를 입력해주세요.",
    "inquiry.contact.details": "상세 요청사항",
    "inquiry.contact.details.placeholder": "원하시는 콘셉트, 사용 목적, 참고하실 브랜드나 이미지가 있다면 함께 적어 주세요.",
    "inquiry.submit": "문의 제출",
    "inquiry.terms.title": "약관 동의",
    "inquiry.privacy.label": "개인정보수집 및 이용 동의(필수) *",
    "inquiry.privacy.agree": "동의합니다",
    "inquiry.privacy.view": "보기",
    "inquiry.success.title": "문의가 정상적으로 접수되었습니다",
    "inquiry.success.desc": "1-2 영업일 안으로 연락드리겠습니다.",
    
    // Works
    "works.title": "WORKS",
    "works.subtitle": "SOBOK에서 기획하고 런칭한 뷰티 브랜드들을 소개합니다",
    "works.launchable": "런칭가능",
    "works.preparing": "준비중",
    "works.more": "자세히 보기",
    "works.cta.title": "나만의 보자기를 만들어보세요",
    "works.cta.desc": "LINEUP 147에서 바로 시작할 수 있는 브랜드를 확인해보세요",
    "works.summary.heading": "소복에서 제작한 맞춤 보자기 프로젝트를 소개합니다",
    "works.summary.viewAll": "더보기",
    "works.cta.button": "문의하고 견적받기",
    "works.brand.milkdive": "밀크다이브",
    "works.brand.puresource": "퓨어소스",
    "works.brand.blankpalette": "Blank Palette",
    "works.brand.wanderlust": "Objet de Wanderlust",
    "works.brand.phaserush": "PHASE RUSH",
    "works.brand.squeelzy": "SQUEELZY",
    "works.category.skincare": "스킨케어",
    "works.category.derma": "더마 브랜드",
    "works.category.makeup": "메이크업",
    "works.category.bodycare": "바디케어",
    "works.desc.milkdive": "피부가 우유를 마실 수 있는 재밌는 상상",
    "works.desc.puresource": "검증된 출처와 최적의 배합의 더마 브랜드",
    "works.desc.blankpalette": "자유롭게 표현하는 메이크업 브랜드",
    "works.desc.wanderlust": "여행의 감성을 담은 바디케어 제품",
    "works.desc.phaserush": "빠른 효과를 위한 단계별 스킨케어",
    "works.desc.squeelzy": "즐거운 메이크업 경험을 위한 브랜드",
    
    // Lineup
    "lineup.title": "LINEUP 147",
    "lineup.subtitle": "상품기획자, 디자이너 없이도 바로 뷰티 브랜드 런칭이 가능하도록",
    "lineup.desc": "브랜드 기획부터 생산까지 SOBOK에서 다 준비해 놨으니까",
    "lineup.launchable": "런칭가능",
    "lineup.preparing": "준비중",
    "lineup.includes": "포함 내용:",
    "lineup.order": "주문하기",
    "lineup.brand.milkdive": "밀크다이브",
    "lineup.brand.puresource": "퓨어소스",
    "lineup.brand.blankpalette": "Blank Palette",
    "lineup.brand.wanderlust": "Objet de Wanderlust",
    "lineup.category.skincare": "스킨케어",
    "lineup.category.derma": "더마 브랜드",
    "lineup.category.makeup": "메이크업",
    "lineup.category.bodycare": "바디케어",
    "lineup.desc.milkdive": "피부가 우유를 마실 수 있는 재밌는 상상",
    "lineup.desc.puresource": "검증된 출처와 최적의 배합의 더마 브랜드",
    "lineup.desc.blankpalette": "자유롭게 표현하는 메이크업 브랜드",
    "lineup.desc.wanderlust": "여행의 감성을 담은 바디케어 제품",
    "lineup.feature1": "완성된 브랜드 컨셉",
    "lineup.feature2": "패키징 디자인",
    "lineup.feature3": "제품 포뮬러",
    "lineup.feature4": "마케팅 자료",
    "lineup.feature5": "의료진 검증 포뮬러",
    "lineup.feature6": "프리미엄 패키징",
    "lineup.feature7": "마케팅 전략",
    "lineup.feature8": "온라인 쇼핑몰 연동",
    "lineup.feature9": "커스터마이징 가능",
    "lineup.feature10": "다양한 컬러 팔레트",
    "lineup.feature11": "지속가능한 포장",
    "lineup.feature12": "크리에이터 협업",
    "lineup.feature13": "여행 테마 컨셉",
    "lineup.feature14": "휴대용 사이즈",
    "lineup.feature15": "자연 유래 성분",
    "lineup.feature16": "글로벌 마케팅",
    "lineup.reason.title": "LINEUP 147이 특별한 이유",
    "lineup.reason.complete": "100%",
    "lineup.reason.complete.desc": "완성된 브랜드",
    "lineup.reason.immediate": "즉시",
    "lineup.reason.immediate.desc": "런칭 가능",
    "lineup.reason.expert": "전문가",
    "lineup.reason.expert.desc": "검증된 품질",
    "lineup.cta.title": "더 많은 정보가 필요하신가요?",
    "lineup.cta.desc": "전문 상담을 통해 맞춤형 솔루션을 제안해드립니다",
    "lineup.cta.button": "상담 신청하기",
    
    // Blog
    "blog.title": "BLOG",
    "blog.subtitle": "SOBOK에서 전하는 화장품 이야기",
    "blog.all": "전체",
    "blog.readMore": "더 읽기",
    "blog.newsletter.title": "SOBOK LETTER 구독하기",
    "blog.newsletter.desc": "뷰티 브랜드 인큐베이터 SOBOK의 최신 소식을 받아보세요",
    "blog.newsletter.button": "뉴스레터 신청하기",
    "blog.category.guide": "가이드",
    "blog.category.trend": "트렌드",
    "blog.category.manufacturing": "제조",
    "blog.category.casestudy": "케이스 스터디",
    "blog.category.sustainability": "지속가능성",
    "blog.category.marketing": "마케팅",
    "blog.post1.title": "뷰티 브랜드 런칭을 위한 첫걸음",
    "blog.post1.excerpt": "뷰티 비즈니스를 시작하고자 하는 분들을 위한 가이드입니다. 브랜드 기획부터 제품 개발까지의 전 과정을 알아봅니다.",
    "blog.post2.title": "AI가 분석한 2024 뷰티 트렌드",
    "blog.post2.excerpt": "LoudLabs의 AI 기술로 분석한 올해의 뷰티 트렌드와 시장 인사이트를 공유합니다.",
    "blog.post3.title": "화장품 제조 과정 완전 정복",
    "blog.post3.excerpt": "화장품이 만들어지는 전 과정을 단계별로 설명합니다. 원료 선정부터 포장까지의 모든 과정을 다룹니다.",
    "blog.post4.title": "성공한 뷰티 브랜드 사례 분석",
    "blog.post4.excerpt": "국내외 성공한 뷰티 브랜드들의 성공 요인을 분석하고, 우리가 배울 수 있는 포인트를 찾아봅니다.",
    "blog.post5.title": "지속가능한 뷰티 브랜드 만들기",
    "blog.post5.excerpt": "환경을 생각하는 뷰티 브랜드를 만드는 방법과 지속가능한 포장재 선택에 대해 알아봅니다.",
    "blog.post6.title": "온라인 쇼핑몰 운영 가이드",
    "blog.post6.excerpt": "뷰티 브랜드의 온라인 쇼핑몰을 성공적으로 운영하기 위한 팁과 전략을 공유합니다.",
    "blog.readtime": "분",
    
    // FAQ
    "faq.title": "FAQ",
    "faq.subtitle": "소복에 자주 들어오는 질문들",
    "faq.q1": "맞춤 제작은 최소 수량이 있나요?",
    "faq.a1": "브랜드 규모와 목적에 맞춰 유연하게 진행합니다. 10장부터 수백 장까지 모두 가능합니다.",
    "faq.q2": "우리 브랜드의 컬러나 로고를 보자기에 적용할 수 있나요?",
    "faq.a2": "가능합니다. 원단 염색, 자수, 직조 패턴 등 다양한 방식으로 브랜드 아이덴티티를 표현해드립니다.",
    "faq.q3": "보자기 제작 기간은 얼마나 걸리나요?",
    "faq.a3": "상담 후 디자인 확정 기준 약 2~3주 내 시제품 제작, 이후 수량에 따라 납기 조정됩니다.",
    "faq.q4": "해외 납품도 가능한가요?",
    "faq.a4": "네, 가능합니다. 글로벌 브랜드와 협업한 경험을 기반으로 안정적인 납품이 가능합니다.",
    "faq.q5": "견적은 어떻게 산정되나요?",
    "faq.a5": "원단 종류, 사이즈, 수량, 인쇄/자수 여부에 따라 산출됩니다. 문의 주시면 구체적인 견적서를 드립니다.",
    "faq.q6": "아직 구체적인 디자인이 없어도 문의할 수 있나요?",
    "faq.a6": "물론입니다. 브랜드의 콘셉트만 알려주셔도 시각적 제안을 드립니다.",
    "faq.search.placeholder": "검색어를 입력해주세요.",
    "faq.search.noResult": "검색결과가 없습니다.",
    "faq.contact.title": "더 궁금한 점이 있으신가요?",
    "faq.contact.desc": "추가 문의사항이 있으시면 언제든지 연락주세요",
    "faq.contact.email": "이메일:",
    "faq.contact.hours": "평일 09:00 - 18:00 (주말 및 공휴일 휴무)",
    
    // Notice
    "notice.title": "공지사항",
    "notice.subtitle": "소복의 주요 소식을 확인하세요",
    "notice.search.placeholder": "검색어를 입력해주세요.",
    "notice.search.noResult": "검색결과가 없습니다.",
    "notice.detail.back": "목록으로",
    "notice.detail.backToList": "목록으로 돌아가기",
    "notice.detail.notFound": "공지사항을 찾을 수 없습니다.",
    "notice.views": "조회",
    "notice.1.title": "서비스 오픈 안내",
    "notice.1.content": "소복 서비스가 2025년 11월 21일에 정식 오픈되었습니다.\n\n맞춤형 보자기 제작 서비스를 통해 브랜드의 감성을 포장하는 가장 간결한 방식을 제공해드리겠습니다.\n\n많은 관심과 이용 부탁드립니다.",
    
    // Footer
    "footer.company": "소복",
    "footer.ceo": "대표 최성락",
    "footer.businessNumber": "사업자등록번호 : 521-87-03693",
    "footer.address": "서울시 동대문구 경희대로 26, 삼의원창업센터 308호",
    "footer.inquiry": "마케팅 및 사업 제휴 문의 : ceo@faddit.co.kr",
    "footer.privacy": "개인정보 처리방침",
    "footer.terms": "이용약관",
    "footer.notice": "공지사항",
    "footer.copyright": "Copyright © SOBOK All rights reserved.",
    
    // Privacy Policy
    "privacy.title": "📄 소복(SOBOK) 개인정보처리방침",
    "privacy.effectiveDate": "시행일: 2025년 11월 19일",
    "privacy.intro1": "소복(SOBOK)(이하 '회사')는 「개인정보 보호법」과 관련 법령을 준수하며, 고객의 개인정보를 안전하게 보호하기 위해 최선을 다하고 있습니다. 본 개인정보처리방침은 보자기 제작 및 상담 서비스 이용과 관련하여 개인정보가 어떤 방식으로 수집·이용·보관·파기되는지 안내하기 위한 것입니다.",
    "privacy.intro2": "본 방침은 서비스 운영 정책에 따라 변경될 수 있으며, 변경 시 웹사이트를 통해 공지합니다.",
    "privacy.section1.title": "1. 수집하는 개인정보 항목",
    "privacy.section1.intro": "회사는 상담 신청 및 문의 접수 시 다음의 개인정보를 수집합니다.",
    "privacy.section1.required.title": "① 필수 수집 항목",
    "privacy.section1.required.item1": "회사명",
    "privacy.section1.required.item2": "담당자명",
    "privacy.section1.required.item3": "연락처(휴대폰 또는 전화번호)",
    "privacy.section1.required.item4": "이메일 주소",
    "privacy.section1.optional.title": "② 선택 수집 항목",
    "privacy.section1.optional.item1": "회사 홈페이지/온라인 채널 주소",
    "privacy.section1.optional.item2": "필요 수량, 납기일 등 프로젝트 정보",
    "privacy.section1.optional.item3": "디자인 파일(브랜드 직조 보자기 요청 시)",
    "privacy.section1.optional.item4": "기타 사용자가 입력한 문의 내용",
    "privacy.section1.auto.title": "③ 자동 수집 항목",
    "privacy.section1.auto.item1": "접속 IP, 방문 일시, 브라우저 정보, 이용기록(쿠키 포함)",
    "privacy.section2.title": "2. 개인정보의 수집 및 이용 목적",
    "privacy.section2.intro": "회사는 수집한 개인정보를 다음의 목적 범위 내에서만 이용합니다.",
    "privacy.section2.purpose1.title": "상담 신청 및 견적 제공",
    "privacy.section2.purpose1.item1": "문의 내용 확인",
    "privacy.section2.purpose1.item2": "상담 연락 및 제작 가능 여부 검토",
    "privacy.section2.purpose1.item3": "파일 기반 목업 제작 및 제안",
    "privacy.section2.purpose2.title": "고객관리 및 서비스 제공",
    "privacy.section2.purpose2.item1": "서비스 제공 관련 안내",
    "privacy.section2.purpose2.item2": "고객 요청 처리 및 커뮤니케이션",
    "privacy.section2.purpose3.title": "서비스 개선 및 내부 기록 관리",
    "privacy.section2.purpose3.item1": "문의 통계 분석",
    "privacy.section2.purpose3.item2": "서비스 품질 개선",
    "privacy.section2.purpose4.title": "법령 준수",
    "privacy.section3.title": "3. 개인정보의 보유 및 이용 기간",
    "privacy.section3.intro": "회사는 개인정보를 다음 기간 동안 보관합니다.",
    "privacy.section3.item1": "문의 및 상담 기록: 3년 보관 후 즉시 파기",
    "privacy.section3.item2": "전자상거래 관련 계약 및 거래 기록: 5년 (해당 시)",
    "privacy.section3.item3": "웹사이트 방문 기록: 3개월",
    "privacy.section3.note": "※ 이용자가 삭제 요청 시 지체 없이 파기됩니다.",
    "privacy.section4.title": "4. 개인정보의 제3자 제공",
    "privacy.section4.content1": "회사는 이용자의 개인정보를 제3자에게 제공하지 않습니다.",
    "privacy.section4.content2": "다만, 법령에 따른 요청이 있는 경우 예외로 합니다.",
    "privacy.section5.title": "5. 개인정보 처리 위탁",
    "privacy.section5.content1": "회사는 원활한 서비스 제공을 위해 다음과 같이 개인정보 처리를 위탁할 수 있습니다.",
    "privacy.section5.content2": "회사는 위탁 시 개인정보 보호 법령 준수 여부를 확인합니다.",
    "privacy.section6.title": "6. 개인정보의 파기 절차 및 방법",
    "privacy.section6.procedure.title": "파기 절차",
    "privacy.section6.procedure.item1": "수집된 개인정보는 보유 기간 경과 또는 처리 목적 달성 시 파기됩니다.",
    "privacy.section6.method.title": "파기 방법",
    "privacy.section6.method.item1": "전자 파일: 복구 불가능한 방식으로 영구 삭제",
    "privacy.section6.method.item2": "출력물: 분쇄 또는 소각",
    "privacy.section7.title": "7. 이용자의 권리",
    "privacy.section7.intro": "이용자는 다음의 권리를 행사할 수 있습니다.",
    "privacy.section7.item1": "개인정보 열람 요구",
    "privacy.section7.item2": "정정·삭제 요구",
    "privacy.section7.item3": "처리 정지 요구",
    "privacy.section7.note": "회사는 본인 확인 후 요청 사항을 처리합니다.",
    "privacy.section8.title": "8. 개인정보 안전성 확보 조치",
    "privacy.section8.intro": "회사는 개인정보 보호를 위해 다음 조치를 시행합니다.",
    "privacy.section8.item1": "접근 권한 최소화",
    "privacy.section8.item2": "비밀번호/파일 암호화",
    "privacy.section8.item3": "접속 로그 및 관리 기록 보관",
    "privacy.section8.item4": "외부 서비스의 보안정책 준수",
    "privacy.section9.title": "9. 쿠키(Cookie) 운영 안내(선택적)",
    "privacy.section9.content1": "회사는 사용자 편의 기능 제공 및 접속 기록 분석을 위해 쿠키를 사용할 수 있습니다.",
    "privacy.section9.content2": "이용자는 웹 브라우저 설정을 통해 쿠키 저장을 거부할 수 있습니다.",
    "privacy.section10.title": "10. 개인정보 보호책임자",
    "privacy.section10.intro": "회사는 이용자의 개인정보를 보호하기 위해 다음과 같이 개인정보보호책임자를 지정합니다.",
    "privacy.section10.officer": "개인정보보호책임자: 김한재",
    "privacy.section10.email": "이메일:",
    "privacy.section10.phone": "연락처:",
    "privacy.section11.title": "11. 고지 의무",
    "privacy.section11.content1": "본 개인정보처리방침은 2025년 11월 19일부터 적용됩니다.",
    "privacy.section11.content2": "변경 사항이 있을 경우 웹사이트 공지를 통해 안내합니다.",
  },
  en: {
    // Header
    "nav.home": "HOME",
    "nav.about": "ABOUT",
    "nav.inquiry": "Inquiry",
    "nav.works": "WORKS",
    "nav.lineup": "LINEUP 147",
    "nav.blog": "BLOG",
    "nav.faq": "FAQ",
    
    // Home
    "home.hero.title": "SOBOK",
    "home.hero.subtitle": "The most concise way to package a brand's sensibility",
    "home.hero.cta": "Request Custom Production",
    
    // Home - Who we are
    "home.who.title": "Who we are",
    "home.who.main": "We don't wrap products.",
    "home.who.sub": "We wrap brands.",
    "home.who.desc": "Packaging is not just wrapping paper. It is an expression of respect, a gesture of care, and a delivery of emotion.\n\nIn Korean tradition, bojagi holds meaning beyond mere fabric. It carries the sincerity and mindset of the giver. Every fold and knot contains intention.\n\nSOBOK means a small but certain blessing, quietly accumulating like snow. Our approach is the same. Subtle but intentional, and lasting.",
    
    "home.lineup.title": "From Brand Planning to Production,\nEverything is Ready at SOBOK",
    "home.lineup.subtitle": "Launch your beauty brand immediately with LINEUP 147,\neven without product planners or designers",
    "home.lineup.cta": "Order LINEUP 147",
    
    "home.loudlabs.title": "We Create Brands\nThat the Market Really Wants",
    "home.loudlabs.subtitle": "LoudLabs uses AI technology to understand market trends and product context,\nplanning new products based on this analysis",
    "home.loudlabs.cta": "Try LoudLabs",
    
    "home.features.easy.title": "Easy",
    "home.features.easy.subtitle": "Simple",
    "home.features.easy.desc": "We provide services across all areas from branding to planning and production for your easy and fast beauty business.",
    "home.features.proven.title": "Proven",
    "home.features.proven.subtitle": "Verified",
    "home.features.proven.desc": "Expert brand planners and researchers plan and test in the actual market to verify planning capabilities.",
    "home.features.reliable.title": "Reliable",
    "home.features.reliable.subtitle": "Trustworthy",
    "home.features.reliable.desc": "We propose to customers based on product model evaluation and prediction algorithms developed using machine learning.",
    
    "home.newsletter.title": "SOBOK LETTER",
    "home.newsletter.subtitle": "Beauty Brand Incubator",
    "home.newsletter.desc": "Cosmetics stories from SOBOK",
    "home.newsletter.placeholder": "Enter your email",
    "home.newsletter.cta": "Subscribe to SOBOK LETTER",
    
    "home.update.title": "Newly Updated Lineup 147",
    "home.update.cta": "Learn More",
    "home.update.brand.milkdive": "Milk Dive",
    "home.update.brand.puresource": "Pure Source",
    "home.update.desc.milkdive": "An interesting imagination of skin drinking milk",
    "home.update.desc.puresource": "A derma brand with verified sources and optimal formulations",
    "home.update.launchable": "Launchable",
    
    // Home - Process
    "home.process.title": "Process",
    "home.process.subtitle": "A thoughtful process for thoughtful gifts",
    "home.process.step1.title": "Brand Consulting",
    "home.process.step1.desc": "We conduct customized consultations to understand your brand, values, and packaging purpose in detail.",
    "home.process.step1.features": "Brand Strategy\nVision Setting\nConcept Definition",
    "home.process.step2.title": "Design & Prototype",
    "home.process.step2.desc": "We propose designs that reflect brand identity and create prototypes.",
    "home.process.step2.features": "Design Proposal\nPrototype Production\nFeedback Integration",
    "home.process.step3.title": "Weaving & Production",
    "home.process.step3.desc": "Based on the confirmed design, master craftsmen directly weave and produce.",
    "home.process.step3.features": "Fabric Selection\nWeaving Work\nQuality Inspection",
    "home.process.step4.title": "Production & Delivery",
    "home.process.step4.desc": "We deliver to the specified location on time with professional packaging.",
    "home.process.step4.features": "Production Management\nDelivery Schedule\nLogistics Shipping",
    "home.process.step5.title": "Archiving & Reorder Service",
    "home.process.step5.desc": "We store your company's data for convenient future reorders.",
    "home.process.step5.features": "Data Management\nReproduction Request\nOrder History",
    
    // Home - Services Feature
    "home.services.feature.title": "Wrapped with Sincerity",
    "home.services.feature.subtitle": "Complete your brand's story with a single bojagi.",
    "home.services.easy.title": "Easy",
    "home.services.easy.korean": "Easy and Conveniently",
    "home.services.easy.desc": "Get the bojagi you need quickly and without hassle. Through customized weaving for each brand and various material options, we reduce complex production processes and unnecessary material waste.",
    "home.services.proven.title": "Proven",
    "home.services.proven.korean": "Verified Quality and Process",
    "home.services.proven.desc": "We systematically manage all stages, from design to weaving, packaging, and delivery. We provide stable results through a production network verified by numerous brand projects and data-driven process management.",
    "home.services.reliable.title": "Reliable",
    "home.services.reliable.korean": "Trustworthy Partner",
    "home.services.reliable.desc": "We accurately understand the quality desired by the brand and produce it responsibly. We transparently share schedules, quality, and costs, and are a reliable partner until delivery.",
    "home.services.custom.title": "Custom Made Bojagi",
    "home.services.custom.percent": "Up to 25%",
    "home.services.custom.price": "Lower Unit Cost",
    "home.services.custom.desc": "Reduce unnecessary material waste through brand-specific custom weaving.",
    "home.services.quality.title": "Schedule & Quality Management System",
    "home.services.quality.delivery": "Delivery Schedule",
    "home.services.quality.guarantee": "100% Guaranteed",
    "home.services.quality.desc": "We manage all processes from design, weaving, packaging to delivery based on data.",
    "home.services.partners": "Companies that have defined brand hearts with SOBOK.",
    
    // Home - CTA
    "home.cta.title": "Inquire Now",
    "home.cta.subtitle": "What fabric suits your brand?",
    "home.cta.desc": "With one bojagi, we complete your brand story.",
    "home.cta.footer": "Packaging is not just a finish, it's the beginning of a brand.",
    "home.cta.button": "Inquire",
    
    // About
    "about.title": "ABOUT SOBOK",
    "about.intro.title": "Brand Introduction",
    "about.intro.desc": "SOBOK is a brand that started with the idea of making moments last longer through packaging. It serves as a bridge between traditional Korean bojagi culture and modern brand packaging.",
    "about.culture.title": "Perspective on Packaging Culture",
    "about.culture.desc": "Korean bojagi culture is a unique tradition that gives meaning to the act of wrapping gifts itself. SOBOK incorporates the value of this tradition into modern brand experiences, providing emotional value beyond simple packaging.",
    "about.values.title": "Values SOBOK Provides",
    "about.values.custom.title": "Custom Patterns That Embody Brand Identity",
    "about.values.custom.desc": "We create completely unique bojagi by directly weaving brand patterns and logos.",
    "about.values.trust.title": "Trust in Manufacturing Process and Quality",
    "about.values.trust.desc": "We provide products of consistent quality through verified manufacturing processes and quality control.",
    "about.values.flexible.title": "Flexible Proposals Tailored to Project Nature",
    "about.values.flexible.desc": "We propose solutions tailored to various projects, from retail brand seasonal promotion packages to commemorative/event gift packages.",
    "about.cases.title": "Production Cases",
    "about.cases.retail": "Retail Brand Seasonal Promotion Package",
    "about.cases.event": "Commemorative/Event Gift Package",
    "about.cta.title": "Shall we start together?",
    "about.cta.desc": "Create a special packaging solution unique to your brand with SOBOK",
    "about.cta.button": "Inquire Now",
    
    // Inquiry
    "inquiry.title": "Consultation & Quote Inquiry",
    "inquiry.subtitle": "Please fill out the inquiry form for bojagi production that fits your project",
    "inquiry.overview.title": "Please double-check before submitting!",
    "inquiry.overview.point1": "SOBOK focuses on branding and packaging design to develop bojagi that are more efficient and sophisticated.",
    "inquiry.overview.point2": "Payment and production do not begin immediately after submitting the inquiry.",
    "inquiry.overview.point3": "A SOBOK specialist will get back to you within 3 business days.",
    "inquiry.profile.title": "Company & Contact Information",
    "inquiry.profile.requiredNote": "indicates required fields.",
    "inquiry.company.title": "Company Information",
    "inquiry.company.name": "Company Name",
    "inquiry.company.name.required": "Required",
    "inquiry.company.name.placeholder": "Please enter your business name or brand name.",
    "inquiry.company.website": "Company Website",
    "inquiry.company.website.placeholder": "You can also leave your website, Instagram, smart store, or other online channel addresses.",
    "inquiry.company.country": "Country",
    "inquiry.company.country.placeholder": "Please select a country.",
    "inquiry.company.industry": "Industry",
    "inquiry.company.industry.placeholder": "Please select or enter your industry.",
    "inquiry.company.industry.custom": "Custom Industry",
    "inquiry.company.industry.custom.placeholder": "e.g. Wellness, Perfume, Living",
    "inquiry.company.products": "Existing Products",
    "inquiry.company.products.placeholder": "Briefly describe products you currently sell or plan to launch.",
    "inquiry.bojagi.title": "Bojagi Type",
    "inquiry.bojagi.regular": "Regular Bojagi",
    "inquiry.bojagi.regular.slab": "Slab",
    "inquiry.bojagi.regular.slab.desc": "Natural texture, warm feeling",
    "inquiry.bojagi.regular.organza": "Organza",
    "inquiry.bojagi.regular.organza.desc": "Semi-transparent, luxurious atmosphere",
    "inquiry.bojagi.regular.crystal": "Crystal",
    "inquiry.bojagi.regular.crystal.desc": "Glossy finish, suitable for events and promotional bulk production",
    "inquiry.bojagi.brand": "Brand Woven Bojagi",
    "inquiry.bojagi.brand.desc": "We can produce woven bojagi using brand patterns, logos, symbols, etc.",
    "inquiry.bojagi.brand.file": "If you have a design file, please attach it. It will be used for mockup production and proposals.",
    "inquiry.bojagi.size.label": "Size",
    "inquiry.bojagi.size.description": "Enter width x height in centimeters. Rough estimates are fine if not finalized.",
    "inquiry.bojagi.size.width": "Width (cm)",
    "inquiry.bojagi.size.height": "Height (cm)",
    "inquiry.bojagi.size.width.placeholder": "e.g. 70",
    "inquiry.bojagi.size.height.placeholder": "e.g. 70",
    "inquiry.supplies.title": "Packaging Supplies",
    "inquiry.supplies.quantity": "Required Quantity",
    "inquiry.supplies.quantity.placeholder": "Please enter the expected quantity",
    "inquiry.supplies.deadline": "Desired Delivery Date",
    "inquiry.supplies.deadline.placeholder": "Please enter the desired delivery date",
    "inquiry.supplies.budget": "Total Budget",
    "inquiry.supplies.budget.placeholder": "Please enter the expected budget (optional)",
    "inquiry.supplies.budget.unit": "KRW",
    "inquiry.contact.title": "Contact Information",
    "inquiry.contact.name": "Contact Name",
    "inquiry.contact.name.required": "Required",
    "inquiry.contact.name.placeholder": "Please enter the contact name.",
    "inquiry.contact.email": "Email",
    "inquiry.contact.email.required": "Required",
    "inquiry.contact.email.placeholder": "Please enter the email address.",
    "inquiry.contact.phone": "Phone",
    "inquiry.contact.phone.required": "Required",
    "inquiry.contact.phone.placeholder": "Please enter the phone number.",
    "inquiry.contact.details": "Detailed Requirements",
    "inquiry.contact.details.placeholder": "Please include your desired concept, purpose of use, and any reference brands or images if available.",
    "inquiry.submit": "Submit Inquiry",
    "inquiry.terms.title": "Terms Agreement",
    "inquiry.privacy.label": "Consent to Collection and Use of Personal Information (Required) *",
    "inquiry.privacy.agree": "I agree",
    "inquiry.privacy.view": "View",
    "inquiry.success.title": "Your inquiry has been successfully received",
    "inquiry.success.desc": "We will contact you within 1-2 business days.",
    
    // Works
    "works.title": "WORKS",
    "works.subtitle": "Introducing beauty brands planned and launched by SOBOK",
    "works.launchable": "Launchable",
    "works.preparing": "Preparing",
    "works.more": "Learn More",
    "works.cta.title": "Create Your Own Bojagi",
    "works.cta.desc": "Check out brands you can start immediately with LINEUP 147",
    "works.summary.heading": "Introducing custom bojagi projects crafted by SOBOK",
    "works.summary.viewAll": "View More",
    "works.cta.button": "Inquire and Get a Quote",
    "works.brand.milkdive": "Milk Dive",
    "works.brand.puresource": "Pure Source",
    "works.brand.blankpalette": "Blank Palette",
    "works.brand.wanderlust": "Objet de Wanderlust",
    "works.brand.phaserush": "PHASE RUSH",
    "works.brand.squeelzy": "SQUEELZY",
    "works.category.skincare": "Skincare",
    "works.category.derma": "Derma Brand",
    "works.category.makeup": "Makeup",
    "works.category.bodycare": "Body Care",
    "works.desc.milkdive": "An interesting imagination of skin drinking milk",
    "works.desc.puresource": "A derma brand with verified sources and optimal formulations",
    "works.desc.blankpalette": "A makeup brand for free expression",
    "works.desc.wanderlust": "Body care products that capture the sentiment of travel",
    "works.desc.phaserush": "Step-by-step skincare for quick results",
    "works.desc.squeelzy": "A brand for joyful makeup experiences",
    
    // Lineup
    "lineup.title": "LINEUP 147",
    "lineup.subtitle": "Launch your beauty brand immediately, even without product planners or designers",
    "lineup.desc": "Everything from brand planning to production is ready at SOBOK",
    "lineup.launchable": "Launchable",
    "lineup.preparing": "Preparing",
    "lineup.includes": "Includes:",
    "lineup.order": "Order Now",
    "lineup.brand.milkdive": "Milk Dive",
    "lineup.brand.puresource": "Pure Source",
    "lineup.brand.blankpalette": "Blank Palette",
    "lineup.brand.wanderlust": "Objet de Wanderlust",
    "lineup.category.skincare": "Skincare",
    "lineup.category.derma": "Derma Brand",
    "lineup.category.makeup": "Makeup",
    "lineup.category.bodycare": "Body Care",
    "lineup.desc.milkdive": "An interesting imagination of skin drinking milk",
    "lineup.desc.puresource": "A derma brand with verified sources and optimal formulations",
    "lineup.desc.blankpalette": "A makeup brand for free expression",
    "lineup.desc.wanderlust": "Body care products that capture the sentiment of travel",
    "lineup.feature1": "Complete brand concept",
    "lineup.feature2": "Packaging design",
    "lineup.feature3": "Product formula",
    "lineup.feature4": "Marketing materials",
    "lineup.feature5": "Medical professional verified formula",
    "lineup.feature6": "Premium packaging",
    "lineup.feature7": "Marketing strategy",
    "lineup.feature8": "Online store integration",
    "lineup.feature9": "Customizable",
    "lineup.feature10": "Various color palettes",
    "lineup.feature11": "Sustainable packaging",
    "lineup.feature12": "Creator collaboration",
    "lineup.feature13": "Travel theme concept",
    "lineup.feature14": "Portable size",
    "lineup.feature15": "Natural ingredients",
    "lineup.feature16": "Global marketing",
    "lineup.reason.title": "Why LINEUP 147 is Special",
    "lineup.reason.complete": "100%",
    "lineup.reason.complete.desc": "Complete Brand",
    "lineup.reason.immediate": "Immediate",
    "lineup.reason.immediate.desc": "Launch Ready",
    "lineup.reason.expert": "Expert",
    "lineup.reason.expert.desc": "Verified Quality",
    "lineup.cta.title": "Need More Information?",
    "lineup.cta.desc": "We offer customized solutions through professional consultation",
    "lineup.cta.button": "Request Consultation",
    
    // Blog
    "blog.title": "BLOG",
    "blog.subtitle": "Cosmetics stories from SOBOK",
    "blog.all": "All",
    "blog.readMore": "Read More",
    "blog.newsletter.title": "Subscribe to SOBOK LETTER",
    "blog.newsletter.desc": "Receive the latest news from beauty brand incubator SOBOK",
    "blog.newsletter.button": "Subscribe to Newsletter",
    "blog.category.guide": "Guide",
    "blog.category.trend": "Trend",
    "blog.category.manufacturing": "Manufacturing",
    "blog.category.casestudy": "Case Study",
    "blog.category.sustainability": "Sustainability",
    "blog.category.marketing": "Marketing",
    "blog.post1.title": "First Steps to Launching a Beauty Brand",
    "blog.post1.excerpt": "A guide for those who want to start a beauty business. Learn about the entire process from brand planning to product development.",
    "blog.post2.title": "2024 Beauty Trends Analyzed by AI",
    "blog.post2.excerpt": "Sharing this year's beauty trends and market insights analyzed by LoudLabs' AI technology.",
    "blog.post3.title": "Complete Guide to Cosmetics Manufacturing Process",
    "blog.post3.excerpt": "Step-by-step explanation of how cosmetics are made. Covers all processes from raw material selection to packaging.",
    "blog.post4.title": "Analysis of Successful Beauty Brand Cases",
    "blog.post4.excerpt": "Analyzing success factors of successful beauty brands domestically and internationally, and finding points we can learn from.",
    "blog.post5.title": "Creating a Sustainable Beauty Brand",
    "blog.post5.excerpt": "Learn about how to create an environmentally conscious beauty brand and choosing sustainable packaging materials.",
    "blog.post6.title": "Online Store Management Guide",
    "blog.post6.excerpt": "Sharing tips and strategies for successfully operating an online store for beauty brands.",
    "blog.readtime": "min",
    
    // FAQ
    "faq.title": "FAQ",
    "faq.subtitle": "Frequently Asked Questions about SOBOK",
    "faq.q1": "Is there a minimum quantity for custom production?",
    "faq.a1": "We proceed flexibly according to brand size and purpose. Everything from 10 pieces to hundreds of pieces is possible.",
    "faq.q2": "Can I apply my brand's colors or logo to the bojagi?",
    "faq.a2": "Yes, it's possible. We express brand identity in various ways such as fabric dyeing, embroidery, and weaving patterns.",
    "faq.q3": "How long does it take to produce bojagi?",
    "faq.a3": "After consultation and design confirmation, prototypes are produced within approximately 2-3 weeks, and delivery dates are adjusted according to quantity thereafter.",
    "faq.q4": "Is international delivery possible?",
    "faq.a4": "Yes, it's possible. Based on our experience collaborating with global brands, we can provide stable delivery.",
    "faq.q5": "How is the estimate calculated?",
    "faq.a5": "It is calculated based on fabric type, size, quantity, and printing/embroidery. Please inquire and we will provide a detailed quote.",
    "faq.q6": "Can I inquire even if I don't have a specific design yet?",
    "faq.a6": "Of course. Just let us know your brand's concept and we will provide visual proposals.",
    "faq.search.placeholder": "Enter search term",
    "faq.search.noResult": "No search results found.",
    "faq.contact.title": "Have More Questions?",
    "faq.contact.desc": "Please contact us anytime if you have additional inquiries",
    "faq.contact.email": "Email:",
    "faq.contact.hours": "Weekdays 09:00 - 18:00 (Closed on weekends and holidays)",
    
    // Notice
    "notice.title": "Notice",
    "notice.subtitle": "Stay updated with SOBOK's latest news",
    "notice.search.placeholder": "Enter search term",
    "notice.search.noResult": "No search results found.",
    "notice.detail.back": "Back to list",
    "notice.detail.backToList": "Back to list",
    "notice.detail.notFound": "Notice not found.",
    "notice.views": "Views",
    "notice.1.title": "Service Launch Announcement",
    "notice.1.content": "SOBOK service officially launched on November 21, 2025.\n\nWe will provide the most concise way to package a brand's sensibility through our custom bojagi production service.\n\nWe appreciate your interest and look forward to serving you.",
    
    // Footer
    "footer.company": "SOBOK",
    "footer.ceo": "CEO Choi Seong-rak",
    "footer.businessNumber": "Business Registration Number: 521-87-03693",
    "footer.address": "26, Kyungheedae-ro, Dongdaemun-gu, Seoul, Samuiwon Startup Center, Room 308",
    "footer.inquiry": "Marketing and Business Partnership Inquiries: ceo@faddit.co.kr",
    "footer.privacy": "Privacy Policy",
    "footer.terms": "Terms of Service",
    "footer.notice": "Notice",
    "footer.copyright": "Copyright © SOBOK All rights reserved.",
    
    // Privacy Policy
    "privacy.title": "📄 SOBOK Privacy Policy",
    "privacy.effectiveDate": "Effective Date: November 19, 2025",
    "privacy.intro1": "SOBOK (hereinafter referred to as 'the Company') complies with the Personal Information Protection Act and related laws, and strives to protect customers' personal information safely. This privacy policy is intended to inform how personal information is collected, used, stored, and destroyed in relation to bojagi production and consultation services.",
    "privacy.intro2": "This policy may be changed according to service operation policies, and will be announced through the website when changed.",
    "privacy.section1.title": "1. Items of Personal Information Collected",
    "privacy.section1.intro": "The company collects the following personal information when applying for consultation or submitting inquiries.",
    "privacy.section1.required.title": "① Required Collection Items",
    "privacy.section1.required.item1": "Company Name",
    "privacy.section1.required.item2": "Contact Person Name",
    "privacy.section1.required.item3": "Contact Information (Mobile Phone or Phone Number)",
    "privacy.section1.required.item4": "Email Address",
    "privacy.section1.optional.title": "② Optional Collection Items",
    "privacy.section1.optional.item1": "Company Website/Online Channel Address",
    "privacy.section1.optional.item2": "Required Quantity, Delivery Date, etc. Project Information",
    "privacy.section1.optional.item3": "Design File (when requesting brand woven bojagi)",
    "privacy.section1.optional.item4": "Other inquiry details entered by the user",
    "privacy.section1.auto.title": "③ Automatic Collection Items",
    "privacy.section1.auto.item1": "Access IP, Visit Date/Time, Browser Information, Usage Records (including cookies)",
    "privacy.section2.title": "2. Purpose of Collection and Use of Personal Information",
    "privacy.section2.intro": "The company uses the collected personal information only within the scope of the following purposes.",
    "privacy.section2.purpose1.title": "Consultation Application and Quotation Provision",
    "privacy.section2.purpose1.item1": "Inquiry content confirmation",
    "privacy.section2.purpose1.item2": "Consultation contact and production feasibility review",
    "privacy.section2.purpose1.item3": "File-based mockup production and proposals",
    "privacy.section2.purpose2.title": "Customer Management and Service Provision",
    "privacy.section2.purpose2.item1": "Service provision-related guidance",
    "privacy.section2.purpose2.item2": "Customer request processing and communication",
    "privacy.section2.purpose3.title": "Service Improvement and Internal Record Management",
    "privacy.section2.purpose3.item1": "Inquiry statistics analysis",
    "privacy.section2.purpose3.item2": "Service quality improvement",
    "privacy.section2.purpose4.title": "Legal Compliance",
    "privacy.section3.title": "3. Retention and Use Period of Personal Information",
    "privacy.section3.intro": "The company retains personal information for the following periods.",
    "privacy.section3.item1": "Inquiry and consultation records: Destroyed immediately after 3 years of retention",
    "privacy.section3.item2": "E-commerce related contracts and transaction records: 5 years (when applicable)",
    "privacy.section3.item3": "Website visit records: 3 months",
    "privacy.section3.note": "※ Personal information will be destroyed immediately upon user's deletion request.",
    "privacy.section4.title": "4. Provision of Personal Information to Third Parties",
    "privacy.section4.content1": "The company does not provide users' personal information to third parties.",
    "privacy.section4.content2": "However, exceptions may be made when required by law.",
    "privacy.section5.title": "5. Personal Information Processing Consignment",
    "privacy.section5.content1": "The company may consign personal information processing as follows for smooth service provision.",
    "privacy.section5.content2": "The company confirms compliance with personal information protection laws when consigning.",
    "privacy.section6.title": "6. Procedures and Methods for Destruction of Personal Information",
    "privacy.section6.procedure.title": "Destruction Procedures",
    "privacy.section6.procedure.item1": "Collected personal information will be destroyed when the retention period expires or the processing purpose is achieved.",
    "privacy.section6.method.title": "Destruction Methods",
    "privacy.section6.method.item1": "Electronic files: Permanent deletion in an irrecoverable manner",
    "privacy.section6.method.item2": "Printed materials: Shredding or incineration",
    "privacy.section7.title": "7. User Rights",
    "privacy.section7.intro": "Users may exercise the following rights.",
    "privacy.section7.item1": "Request to access personal information",
    "privacy.section7.item2": "Request for correction or deletion",
    "privacy.section7.item3": "Request to suspend processing",
    "privacy.section7.note": "The company processes requests after identity verification.",
    "privacy.section8.title": "8. Measures to Ensure Personal Information Security",
    "privacy.section8.intro": "The company implements the following measures to protect personal information.",
    "privacy.section8.item1": "Minimization of access rights",
    "privacy.section8.item2": "Password/file encryption",
    "privacy.section8.item3": "Storage of access logs and management records",
    "privacy.section8.item4": "Compliance with external service security policies",
    "privacy.section9.title": "9. Cookie Operation Guide (Optional)",
    "privacy.section9.content1": "The company may use cookies to provide user convenience features and analyze access records.",
    "privacy.section9.content2": "Users can refuse cookie storage through web browser settings.",
    "privacy.section10.title": "10. Personal Information Protection Officer",
    "privacy.section10.intro": "The company designates a personal information protection officer as follows to protect users' personal information.",
    "privacy.section10.officer": "Personal Information Protection Officer: Kim Han-jae",
    "privacy.section10.email": "Email:",
    "privacy.section10.phone": "Contact:",
    "privacy.section11.title": "11. Notice Obligation",
    "privacy.section11.content1": "This privacy policy takes effect from November 19, 2025.",
    "privacy.section11.content2": "Any changes will be announced through the website.",
  }
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("ko")

  const toggleLanguage = () => {
    setLanguage(prev => prev === "ko" ? "en" : "ko")
  }

  const t = (key: string): string => {
    const langTranslations = translations[language] as Record<string, string>
    return langTranslations[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}

